onestone2team/StoneCoffee_Frontend

.vscode/settings.json
checkout.html
css/checkout.css
js/all_data.js
js/checkout.js

- 주문 상품 박스/ 배송지 입력박스 분리
- 주문 상품 박스에 최종결제금액란 추가
- 배송지 입력란에 유저 정보 불러오기
CLOSES #50

feat: 결제페이지 수정

---

admin_inquiry.html
admin_order_list.html
createproduct.html
css/header.css
header.html
js/admin_inquiry.js
js/admin_order_list.js
js/all_data.js
js/header.js
wishlist.html

- 로그인 시 로그인한 사람의 이름을 payload 에서 읽어서 ooo님 이라고 나오게 수정
- admin 로그인 시 이름을 눌렀을때 admin_order_list 로 이동하도록 수정
CLOSE #37

update: 로그인 시 이름 변경, admin일때 주소 변경

---

admin_inquiry.html
admin_order_list.html
cart.html
createproduct.html
css/header_user.css
header_admin.html
header_user.html
inquiry.html
inquiry_list.html
js/admin_inquiry.js
js/admin_order_list.js
js/all_data.js
js/cart.js
js/createproduct.js
js/header.js
js/inquiry.js
js/inquiry_list.js
js/my_order_list.js
js/profile_edit.js
js/wishlist.js
my_order_list.html
profile_edit.html
wishlist.html

update: 관리자 및 마이페이지 카테고리 바 추가 #38

---

cart.html
css/cart.css
css/detail.css
css/my_order_list.css
index.html
js/all_data.js
js/cart.js
js/my_order_list.js
js/productdetail.js
mainAll.html
my_order_list.html
product-detail.html

- 모바일을 위한 페이지 변경~
- before
-after

Fix/cart #47

---

css/profile_edit.css
js/profile_edit.js
profile_edit.html

- 페이지 디자인 변경 완료
- 각 입력 항목 별 유효성 검사 관련 사항 안내 기능 추가
- 프로필 최초 수정시 partial=True 적용되지 않는 부분은 백엔드에서 처리
- 폰트, 프로필 사진 px->% 변경하지 않아도 문제 없음
CLOSES #41

update: 프로필 수정 페이지 업데이트

---

css/cart.css
css/inquiry_list.css
inquiry_list.html
js/all_data.js
js/inquiry_list.js

- inquiry페이지 변경, 모바일에서도 잘 보이게 변경

fix: inquiry_list

---

js/search.js
search.html

update: search 페이지네이션 수정

---

js/search.js

- 최대 페이지 미지정으로 인해 최대페이지 지정
- N/A

update: pagenation 최대 페이지 오류 수정

---

css/stylecategory.css
mainAll.html
search.html

- search,categroy 중복 수정 관련 css 파일 추가
- N/A

update: search,categroy 중복 수정 관련 css 파일 추가

---

css/inquiry.css
css/my_order_list.css

모바일 사이즈 변경

---

css/detail.css
css/survey.css
js/survey.js
product-detail.html
survey.html

update: 모바일 화면 비율에 맞게 수정

---

css/header.css

update: 검색창 버튼 색깔 고정

---

checkout.html
css/checkout.css
css/payment.css
js/checkout.js
js/payment.js
payment.html

- 결제 시 결제 되야 넘어가도록 설정
- 결제 이후 넘어가는 화면 추가
- 동의 check 안하면 다음페이지 안넘어가도록 수정

feat: 테스트 결제 기능 추가

---

css/wishlist.css
js/wishlist.js

- 상품 사진 하단에 상품 이름 추가
- 모바일 사진 크기 수정

Update/wishlist #103

---

cart.html
css/cart.css
js/all_data.js
js/cart.js
js/header.js

#99 장바구니 이미지(모바일포함)크기 조정, 숫자  , 찍기  삭제시 confirm 

---

css/my_order_list.css
js/my_order_list.js

구매목록 용량 오류수정 및 수량단위 금액단위 수정

---

checkout.html
js/checkout.js

결제하기 페이지 수정

---

css/profile_edit.css
header.html
js/header.js
js/profile_edit.js
profile_edit.html

- 기존 프로필 페이지에 들어갔을때 input 박스에서 일반 글자로 변경
- 프로필 수정 누를시 input 박스로 바뀌고 버튼 변경
- 기존 비밀번호 버튼 변경 후 톱니바퀴모양은 프로필 이미지 수정으로 변경
- 비밀번호 누를시 자동으로 - 모양 추가
처음 화면
수정 누를시
비밀번호 자동 -
#101

update: 프로필 수정 UI 변경 및 input box 변경

---

comment_copy.html
css/comment_copy.css
js/comment_copy.js

update: 댓글 상세페이지 좋아요 비동기로 수정

---

css/profile_edit.css
css/stylecategory.css
js/maincategory.js
js/search.js
mainAll.html

- 7이하일때 페이지네이션 최대 페이지 숫자 안없어 지는거 수정
- 산미, 바디감일때 내림차순, 오름차순 기능 추가
페이지네이션
내림차순 오름차순
CLOSE #96

update: category 페이지 수정 #96

---

css/detail.css
js/productdetail.js
js/survey.js
product-detail.html

- product detail page 라디오 버튼, 버튼 이미지 변경, 좋아요 실시간 적용, 금액 알아보기 쉽게 적용

Update/wishlist #97

---

index.html
js/cart.js

fix : cart.html 계산똑바로 안되던거 수정

---

js/productdetail.js
product-detail.html

 fix : product.html cart() 실행시 문자열로 가격넘어오던것 수정

---

header.html
js/header.js
js/mainslide.js
js/rolling.js

fix 검색창 enter키 사용가능

---

css/survey.css
js/survey.js
survey.html

- 로그인이 되어있는 상태라면 회원가입 페이지가 아닌 상세 페이지로 이동
- 설문조사 UI 몇몇 부분 화면이 작아지면 이상해져 수정
CLOSE #117

update: 설문조사 페이지 UI 변경 및 로그인시 상세 페이지 이동 #117

---

css/header_user.css
js/signupin.js
signupin.html

-비밀번호에 숫자필수인 부분 안내 문구 추가하기
-로그인 알럿 없애기
-엔터키 활성화
-비밀번호에 숫자필수인 부분 안내 문구 추가하기
BEFORE
AFTER
-로그인 알럿 없애기
BEFORE
AFTER
로그인이 완료되면 바로 메인화면으로 넘어가게 
-엔터키 활성화
로그인 실행할때 password입력후 엔터키 활성화
email과 passwrod입력후 password박스에서 엔터키누르면
login 실행되어 main으로 이동

[BUG & FEATURE] 회원가입 및 로그인 #94

---

js/profile_edit.js

- 우편번호를 입력 안했을때 () 가 생기는 버그 수정
변경 후
CLOSE #134

update: profile 오류 수정

---

admin_order_list.html
css/admin_order_list.css
js/admin_order_list.js
js/header.js

로그인세션만료시 alert문구와함깨 로그아웃후 메인페이지,admin_order_list 수정

---

css/header.css
css/payment.css
header.html
header_user.html
js/comment_copy.js

update: 댓글 상세페이지, 헤더, payment페이지 일부 수정

---

checkout.html
css/header_user.css
css/my_order_list.css
js/comment_copy.js
js/header.js
js/my_order_list.js

update: 주문목록 페이지 주문취소기능 연결

---

404.html
admin_inquiry.html
cart.html
checkout.html
comment_copy.html
createproduct.html
header-test.html
inquiry.html
inquiry_list.html
js/cart.js
js/comment_copy.js
js/header.js
js/my_order_list.js
js/productdetail.js
js/survey.js
js/wishlist.js
mainAll.html
product.html
search.html

cart.html 에서  그람수 안보이는거 수정

---

css/index.css
css/survey.css
index.html
js/header.js
js/index.js
js/survey.js
mainAll.html

update: 유저 추천 시스템 적용

---

js/all_data.js
js/productdetail.js

- product detail에서 가격 잘못 전달되는 현상 고침

hotfix: 커피용품 가격 잘못전달 되는 것
